var express = require('express');
var router = express.Router();

/* GET users listing. */
router.get('/', function (req, res, next) {
  var dataArray = [{
    "id": "33",
    "post_author": "2",
    "post_keywords": "0",
    "post_source": "Gamepoch",
    "post_date": "2017-01-13 16:50:56",
    "post_content": "<p><span style=\"font-size:13px;font-family: &#39;Segoe UI&#39;,sans-serif\">The finals of KOF14 China National E-sports Campaign is about to kick off in Shanghai on January 14<sup>th</sup> , 2017.</span></p><p><br/></p><p style=\"text-align: center;\"><img src=\"http://139.196.239.213/thinkcmf/data/upload/ueditor/20170113/587894a80777e.jpg\" title=\"1.jpg\" alt=\"1.jpg\"/></p><h2><span style=\"font-size:16px;line-height:173%;font-family:&#39;Segoe UI&#39;,sans-serif\">The game live broadcast will give you an unprecedented audio-visual feast as same as the variety show.</span></h2><p><span style=\"font-size:13px;font-family:&#39;Segoe UI&#39;,sans-serif\">As the organizer of the campaign, Gamepoch will cooperate with Hunan Beimian Culture Media Co., Ltd, which once participated in the production of popular variety show “Super Boy” and global campaign ”WBA” and “World Wing Outfit Flight Challenge”, to plan the live broadcast of the finals.</span></p><p><span style=\"font-size:13px;font-family:&#39;Segoe UI&#39;,sans-serif\">Time: 13:00-18:00, January 14<sup>th</sup> , 2017</span></p><p><span style=\"font-size:13px;font-family:&#39;Segoe UI&#39;,sans-serif\">Place: ESR Gaming Hall, floor 4, No.755, Huaihai Road, Huangpu district, Shanghai</span></p><h2><span style=\"font-size:16px;line-height:173%;font-family:&#39;Segoe UI&#39;,sans-serif\">Let’s witness the birth of the Chinese dream team!</span></h2><p><span style=\"font-size:13px;font-family:&#39;Segoe UI&#39;,sans-serif\">The campaign will take double-elimination campaign format, those players who lost two games will be eliminated directly. Except the finals, all formats are BO3 and format of the finals is BO5. The winner group has no advantage.&nbsp;</span></p><p><br/></p><p style=\"text-align: center;\"><img src=\"http://139.196.239.213/thinkcmf/data/upload/ueditor/20170113/587894c144630.png\" title=\"2.png\" alt=\"2.png\"/></p><p><br/></p><p><span style=\"font-size:13px;font-family: &#39;Segoe UI&#39;,sans-serif\">List of 16 players:</span></p><p><span style=\"font-size:13px;font-family: &#39;Segoe UI&#39;,sans-serif\"><br/></span></p><p style=\"text-align: center;\"><span style=\"font-size:13px;font-family: &#39;Segoe UI&#39;,sans-serif\"><img src=\"http://139.196.239.213/thinkcmf/data/upload/ueditor/20170113/587894c87c68b.png\" title=\"3.png\" alt=\"3.png\"/></span></p><p><span style=\"font-size:13px;font-family: &#39;Segoe UI&#39;,sans-serif\"><br/></span></p><p><span style=\"font-size:13px;font-family: &#39;Segoe UI&#39;,sans-serif\"></span></p><p><span style=\"font-size:13px;font-family:&#39;Segoe UI&#39;,sans-serif\">The top three of this campaign will participate in the “</span><span style=\"font-size:13px;font-family:&#39;Segoe UI&#39;,sans-serif\">KOF XIV WORLD CHAMPIONSHIP”</span><span style=\"font-size:13px;font-family:&#39;Segoe UI&#39;,sans-serif\"> on behalf of Chinese team </span><span style=\"font-size:13px;font-family:&#39;Segoe UI&#39;,sans-serif\">on February 18<sup>th</sup>, 2017.</span></p><p><span style=\"font-size:13px;font-family: &#39;Segoe UI&#39;,sans-serif\"></span><br/></p><p style=\"text-align: center;\"><img src=\"http://139.196.239.213/thinkcmf/data/upload/ueditor/20170113/587894d1de22e.jpg\" title=\"4.jpg\" alt=\"4.jpg\"/></p><h2><span style=\"font-size:16px;line-height:173%;font-family:&#39;Segoe UI&#39;,sans-serif\">VIP studded, welfare delivery never stops!</span></h2><p><span style=\"font-size:13px;font-family:&#39;Segoe UI&#39;,sans-serif\">Except for 16 players, Gamepoch also invites Takehito Soeda, the president of SONY interactive entertainment (Shanghai) Co., Ltd. Steven Hu, the CEO of Ourpalm, Yasuyuki Oda, the game producer of KOF XIV, Chen Yibiao, Strategic Shareholder of iRENA and LGD, the well-known gaming club. </span></p><p><span style=\"font-size:13px;font-family:&#39;Segoe UI&#39;,sans-serif\">Audiences will have the opportunity to get the genuine KOF14 suit which has the autograph of Yasuyuki Oda, the game producer of KOF14 and official souvenirs. </span></p><p><span style=\"font-size:13px;font-family:&#39;Segoe UI&#39;,sans-serif\">Battle will be triggered at any moment!</span></p><p><span style=\"font-size:13px;font-family: &#39;Segoe UI&#39;,sans-serif\"><br/></span></p><p><br/></p>",
    "post_title": "KOF14 China National E-sports Campaign Started, Cherry Video Platform Witnesses the Birth of the King",
    "post_excerpt": "The finals of KOF14 China National E-sports Campaign is about to kick off in Shanghai on January 14th , 2017.",
    "post_status": "1",
    "comment_status": "1",
    "post_modified": "2017-01-13 16:47:21",
    "post_content_filtered": null,
    "post_parent": "0",
    "post_type": null,
    "post_mime_type": "",
    "comment_count": "0",
    "smeta": "{\"thumb\":\"587894e97be1b.jpg\"}",
    "post_hits": "2",
    "post_like": "0",
    "istop": "0",
    "recommended": "0",
    "post_net": "gamepoch.com",
    "tid": "33",
    "object_id": "33",
    "term_id": "1",
    "listorder": "4",
    "status": "1"
  }, {
    "id": "3",
    "post_author": "2",
    "post_keywords": "0",
    "post_source": "Gamepoch",
    "post_date": "2016-12-05 13:38:57",
    "post_content": "<p style=\"text-align: center;\"><img src=\"http://139.196.239.213/thinkcmf/data/upload/ueditor/20161226/5860accc833d0.jpg\"/></p><p>SNK announces that KOF XIV will have a large free update probably in January 2017. Game version will be upgraded to 1.10. And Ver.1.10 version’s demo2 will be released synchronously on a global scale in December which is free in China store!</p><p style=\"text-align: center;\"><img src=\"http://139.196.239.213/thinkcmf/data/upload/ueditor/20161226/5860acd271134.png\"/></p><p><br/></p><p>Contents of 1.10 Version Update:&nbsp;</p><p>1. Enhance the image performance&nbsp;</p><p>2. Added the Color change of character appearance from 4 to 6&nbsp;</p><p>3. Some other update about game optimization</p><p style=\"text-align: center;\"><img class=\"articleImg\" src=\"http://139.196.239.213/thinkcmf/data/upload/ueditor/20161226/5860ace01521b.jpg\" style=\"box-sizing: border-box; border: 0px; vertical-align: middle; width: 919.5px; margin: 20px auto; color: rgb(117, 117, 117); font-family: &#39;Arial Unicode MS&#39;, 宋体, &#39;Segoe UI&#39;, &#39;Lucida Grande&#39;, Helvetica, Arial, sans-serif, FreeSans, Arimo; font-size: 16.8px; line-height: 24px; white-space: normal; background-color: rgb(235, 235, 235);\"/><span style=\"color: rgb(117, 117, 117); font-family: &#39;Arial Unicode MS&#39;, 宋体, &#39;Segoe UI&#39;, &#39;Lucida Grande&#39;, Helvetica, Arial, sans-serif, FreeSans, Arimo; font-size: 16.8px; line-height: 24px; background-color: rgb(235, 235, 235);\"></span><img class=\"articleImg\" src=\"http://139.196.239.213/thinkcmf/data/upload/ueditor/20161226/5860ace105885.jpg\" style=\"box-sizing: border-box; border: 0px; vertical-align: middle; width: 919.5px; margin: 20px auto; color: rgb(117, 117, 117); font-family: &#39;Arial Unicode MS&#39;, 宋体, &#39;Segoe UI&#39;, &#39;Lucida Grande&#39;, Helvetica, Arial, sans-serif, FreeSans, Arimo; font-size: 16.8px; line-height: 24px; white-space: normal; background-color: rgb(235, 235, 235);\"/><span style=\"color: rgb(117, 117, 117); font-family: &#39;Arial Unicode MS&#39;, 宋体, &#39;Segoe UI&#39;, &#39;Lucida Grande&#39;, Helvetica, Arial, sans-serif, FreeSans, Arimo; font-size: 16.8px; line-height: 24px; background-color: rgb(235, 235, 235);\"></span><img class=\"articleImg\" src=\"http://139.196.239.213/thinkcmf/data/upload/ueditor/20161226/5860ace20ce67.jpg\" style=\"box-sizing: border-box; border: 0px; vertical-align: middle; width: 919.5px; margin: 20px auto; color: rgb(117, 117, 117); font-family: &#39;Arial Unicode MS&#39;, 宋体, &#39;Segoe UI&#39;, &#39;Lucida Grande&#39;, Helvetica, Arial, sans-serif, FreeSans, Arimo; font-size: 16.8px; line-height: 24px; white-space: normal; background-color: rgb(235, 235, 235);\"/><span style=\"color: rgb(117, 117, 117); font-family: &#39;Arial Unicode MS&#39;, 宋体, &#39;Segoe UI&#39;, &#39;Lucida Grande&#39;, Helvetica, Arial, sans-serif, FreeSans, Arimo; font-size: 16.8px; line-height: 24px; background-color: rgb(235, 235, 235);\"></span><img class=\"articleImg\" src=\"http://139.196.239.213/thinkcmf/data/upload/ueditor/20161226/5860ace30fe6d.jpg\" style=\"box-sizing: border-box; border: 0px; vertical-align: middle; width: 919.5px; margin: 20px auto; color: rgb(117, 117, 117); font-family: &#39;Arial Unicode MS&#39;, 宋体, &#39;Segoe UI&#39;, &#39;Lucida Grande&#39;, Helvetica, Arial, sans-serif, FreeSans, Arimo; font-size: 16.8px; line-height: 24px; white-space: normal; background-color: rgb(235, 235, 235);\"/><span style=\"color: rgb(117, 117, 117); font-family: &#39;Arial Unicode MS&#39;, 宋体, &#39;Segoe UI&#39;, &#39;Lucida Grande&#39;, Helvetica, Arial, sans-serif, FreeSans, Arimo; font-size: 16.8px; line-height: 24px; background-color: rgb(235, 235, 235);\"></span><img class=\"articleImg\" src=\"http://139.196.239.213/thinkcmf/data/upload/ueditor/20161226/5860ace472855.jpg\" style=\"box-sizing: border-box; border: 0px; vertical-align: middle; width: 919.5px; margin: 20px auto; color: rgb(117, 117, 117); font-family: &#39;Arial Unicode MS&#39;, 宋体, &#39;Segoe UI&#39;, &#39;Lucida Grande&#39;, Helvetica, Arial, sans-serif, FreeSans, Arimo; font-size: 16.8px; line-height: 24px; white-space: normal; background-color: rgb(235, 235, 235);\"/>&nbsp;&nbsp;</p><p>KOF XIV 1.10 version is coming soon.</p><p><br/></p>",
    "post_title": "KOF XIV 1.10 Version is Coming Soon！A New Audio-visual Feast is On the Way. Are You Ready?",
    "post_excerpt": "SNK announces KOFXIV will have a large free update probably in January 2017. Game version will be upgraded to 1.10.   ",
    "post_status": "1",
    "comment_status": "1",
    "post_modified": "2016-12-26 13:37:14",
    "post_content_filtered": null,
    "post_parent": "0",
    "post_type": null,
    "post_mime_type": "",
    "comment_count": "0",
    "smeta": "{\"thumb\":\"5860acee916eb.jpg\"}",
    "post_hits": "0",
    "post_like": "0",
    "istop": "0",
    "recommended": "0",
    "post_net": "gamepoch.com",
    "tid": "3",
    "object_id": "3",
    "term_id": "1",
    "listorder": "3",
    "status": "1"
  }, {
    "id": "2",
    "post_author": "2",
    "post_keywords": "0",
    "post_source": "Gamepoch",
    "post_date": "2016-12-02 13:33:52",
    "post_content": "<h2>A costume card</h2><h2 style=\"text-align: center;\"><img src=\"http://139.196.239.213/thinkcmf/data/upload/ueditor/20161226/5860aab019993.jpg\"/></h2><p>At first, KOF XIV premium edition of China contains China limited contents, IORI YAGAMI classic costume DLC verification code</p><p style=\"text-align: center;\"><img src=\"http://139.196.239.213/thinkcmf/data/upload/ueditor/20161226/5860aadcc1791.jpg\"/></p><p>Players can get IORI YAGAMI classic costume by following the tips on the back of the card. And this card also has another important use.</p><p>Players can use their own verification code to register in the KOF XIV official website: KOF.gamepoch.com.</p><p>After the authentication is passed, all later costume DLC will be free for those players who was already pass the authentication.</p><p style=\"text-align: center;\"><img src=\"http://139.196.239.213/thinkcmf/data/upload/ueditor/20161226/5860aaeb8ed54.jpg\"/></p><p style=\"text-align: center;\">(Click the link on the home page)</p><p style=\"text-align: center;\"><img src=\"http://139.196.239.213/thinkcmf/data/upload/ueditor/20161226/5860aaf743320.jpg\"/></p><p style=\"text-align: center;\">(Input the required information, click confirm and waiting for verification)</p><p style=\"text-align: center;\"><img src=\"http://139.196.239.213/thinkcmf/data/upload/ueditor/20161226/5860ab00735f8.jpg\"/></p><p><br/></p><p style=\"text-align: center;\">(Verification passed! Get free costume from now on.)</p><p><br/></p><h2>Steelbook</h2><p style=\"text-align: center;\"><img src=\"http://139.196.239.213/thinkcmf/data/upload/ueditor/20161226/5860ab11483d8.jpg\"/></p><p>In order to show the color and texture perfectly, we used the most sophisticated film covering technology.</p><p style=\"text-align: center;\"><img src=\"http://139.196.239.213/thinkcmf/data/upload/ueditor/20161226/5860ab1cae27e.jpg\"/></p><p>For achieving the naked eye 3D effects, we used multilayer printing to make sense of hierarchy.</p><p style=\"text-align: center;\"><img src=\"http://139.196.239.213/thinkcmf/data/upload/ueditor/20161226/5860ab26abc8f.jpg\"/></p><p>It includes visual effects as well as another technique on arms, embossed printing.</p><p><br/></p><h2>KOF XIV Art book</h2><p style=\"text-align: center;\"><img src=\"http://139.196.239.213/thinkcmf/data/upload/ueditor/20161226/5860ab3f4d094.jpg\"/></p><p>The art book printed with full-color printing, and used quality paper to ensure the quality of binding.</p><p style=\"text-align: center;\"><img src=\"http://139.196.239.213/thinkcmf/data/upload/ueditor/20161226/5860ab49d50ee.jpg\"/></p><p style=\"text-align: center;\">(what does Iori Yagami wear under the coat?)</p><p style=\"text-align: center;\"><img src=\"http://139.196.239.213/thinkcmf/data/upload/ueditor/20161226/5860ab50cdf9d.jpg\"/></p><p style=\"text-align: center;\">（Chinese-Japanese bilingual）</p><p style=\"text-align: center;\"><img src=\"http://139.196.239.213/thinkcmf/data/upload/ueditor/20161226/5860ab678d5f6.jpg\"/></p><p style=\"text-align: center;\">&nbsp;<img src=\"http://139.196.239.213/thinkcmf/data/upload/ueditor/20161226/5860ab68a764d.jpg\"/></p><h2>Other centerpieces:</h2><p>Steelbook interior design: 4-disc blue-ray with tray.</p><p style=\"text-align: center;\"><img class=\"articleImg\" src=\"http://139.196.239.213/thinkcmf/data/upload/ueditor/20161226/5860ab7defb9b.jpg\" style=\"box-sizing: border-box; border: 0px; vertical-align: middle; width: 919.5px; margin: 20px auto; color: rgb(117, 117, 117); font-family: &#39;Arial Unicode MS&#39;, 宋体, &#39;Segoe UI&#39;, &#39;Lucida Grande&#39;, Helvetica, Arial, sans-serif, FreeSans, Arimo; font-size: 16.8px; line-height: 24px; white-space: normal; background-color: rgb(235, 235, 235);\"/><span style=\"color: rgb(117, 117, 117); font-family: &#39;Arial Unicode MS&#39;, 宋体, &#39;Segoe UI&#39;, &#39;Lucida Grande&#39;, Helvetica, Arial, sans-serif, FreeSans, Arimo; font-size: 16.8px; line-height: 24px; background-color: rgb(235, 235, 235);\"></span><img class=\"articleImg\" src=\"http://139.196.239.213/thinkcmf/data/upload/ueditor/20161226/5860ab7f33a03.jpg\" style=\"box-sizing: border-box; border: 0px; vertical-align: middle; width: 919.5px; margin: 20px auto; color: rgb(117, 117, 117); font-family: &#39;Arial Unicode MS&#39;, 宋体, &#39;Segoe UI&#39;, &#39;Lucida Grande&#39;, Helvetica, Arial, sans-serif, FreeSans, Arimo; font-size: 16.8px; line-height: 24px; white-space: normal; background-color: rgb(235, 235, 235);\"/><span style=\"color: rgb(117, 117, 117); font-family: &#39;Arial Unicode MS&#39;, 宋体, &#39;Segoe UI&#39;, &#39;Lucida Grande&#39;, Helvetica, Arial, sans-serif, FreeSans, Arimo; font-size: 16.8px; line-height: 24px; background-color: rgb(235, 235, 235);\"></span><img class=\"articleImg\" src=\"http://139.196.239.213/thinkcmf/data/upload/ueditor/20161226/5860ab80f1c99.jpg\" style=\"box-sizing: border-box; border: 0px; vertical-align: middle; width: 919.5px; margin: 20px auto; color: rgb(117, 117, 117); font-family: &#39;Arial Unicode MS&#39;, 宋体, &#39;Segoe UI&#39;, &#39;Lucida Grande&#39;, Helvetica, Arial, sans-serif, FreeSans, Arimo; font-size: 16.8px; line-height: 24px; white-space: normal; background-color: rgb(235, 235, 235);\"/></p><p>&nbsp;&nbsp;</p><p>Purchase address of KOF XIV Premium Edition in China store:</p><p><br/></p><p>https://detail.tmall.com/item.htm?spm=a220m.1000858.0.0.CyDrFz&amp;id=541738768526&amp;skuId=3417638891908&amp;is_b=1&amp;cat_id=2&amp;q=%C8%AD%BB%CA+14</p><p><br/></p>",
    "post_title": "A Over-valued Product, KOF XIV Premium Edition Shot and Analysis",
    "post_excerpt": "At first, KOFXIV premium edition of China contains China limited contents, IORI YAGAMI  costume DLC verification code    ",
    "post_status": "1",
    "comment_status": "1",
    "post_modified": "2016-12-26 13:28:29",
    "post_content_filtered": null,
    "post_parent": "0",
    "post_type": null,
    "post_mime_type": "",
    "comment_count": "0",
    "smeta": "{\"thumb\":\"5860ab992020e.jpg\"}",
    "post_hits": "0",
    "post_like": "0",
    "istop": "0",
    "recommended": "0",
    "post_net": "gamepoch.com",
    "tid": "2",
    "object_id": "2",
    "term_id": "1",
    "listorder": "2",
    "status": "1"
  }, {
    "id": "1",
    "post_author": "2",
    "post_keywords": "0",
    "post_source": "Gamepoch",
    "post_date": "2016-10-24 13:27:15",
    "post_content": "<p style=\"text-indent: 28px\">In October 24th, SONY launched PlayStation@ China Publisher &amp; Developer Meeting in Renaissance Shanghai Zhongshan Park Hotel . During the meeting, SONY showed the developing process and excellent achievement of the Asian-Pacific region especially China.</p><p style=\"text-align: center;\">&nbsp;<img src=\"http://139.196.239.213/thinkcmf/data/upload/ueditor/20161226/5860a90d6eb21.jpg\"/></p><p>&nbsp; &nbsp;<span style=\"text-indent: 28px;\">In this meeting, after announcing that China has won the best appointment grade of PS VR Asia-pacific region and will fully introduce overseas first-class game into China, Sony announced that Gamepoch “star singularity alliance” officially launched.</span></p><p>&nbsp;</p><h2 style=\"font-size: 32px; font-weight: bold; border-bottom-color: rgb(204, 204, 204); border-bottom-width: 2px; border-bottom-style: solid; padding: 0px 4px 0px 0px; text-align: left; margin: 0px 0px 10px;\"><span style=\"font-size: 24px;\"><strong>PS VR Asia pre-sale point which SONY officially licensed</strong></span></h2><p style=\"text-indent: 28px\">As the latest main product of SONY, all eyes are fixed on trans-era product PS VR form pre-sale period.</p><p style=\"text-align: center;\">&nbsp;<img src=\"http://139.196.239.213/thinkcmf/data/upload/ueditor/20161226/5860a96e93ba7.jpg\"/></p><p style=\"text-indent: 28px\">In the summer of 2016, as one of the pre-sale point which got the earliest official authorization, Gamepoch Set up ” Star Game, New Experience PS VR Experience meeting” in Shanghai Global Harbor.</p><p style=\"text-align: right;\">&nbsp;<img src=\"http://139.196.239.213/thinkcmf/data/upload/ueditor/20161226/5860a98226c67.jpg\"/><img src=\"http://139.196.239.213/thinkcmf/data/upload/ueditor/20161226/5860a992f2e40.jpg\"/></p><p style=\"text-indent: 28px\">In the experience Museum, Gamepoch Combined experience with pre-sale, allow the experiencer to fully feel the charm of VR and complete the VR pre-sale activities successfully.</p><p>&nbsp;</p><h1 label=\"标题居左\" style=\"font-size: 32px; font-weight: bold; border-bottom-color: rgb(204, 204, 204); border-bottom-width: 2px; border-bottom-style: solid; padding: 0px 4px 0px 0px; text-align: left; margin: 0px 0px 10px;\"><span style=\"font-size: 24px;\"><strong>An excellent game service provider that keep the whole world in view</strong></span></h1><p>&nbsp; &nbsp;As an important partner of Sony in China, Gamepoch was listed as one of the top three publishers and been introduced emphatically in the meeting. At present, SONY&#39;s main work is to develop overseas boutique masterpiece into Chinese Market. Oda Hirono, executive vice president of SONY interactive entertainment Japan, whom did a detailed explanation by using Gamepoch issued “KOF14” Chinese licensed version as an example on this point. It can be said that this is based on the &quot;KOF14&quot; sales of Chinese licensed version and the previous cases of outstanding issues. Meanwhile, it’s the high recognition of Gamepoch&#39;s performance.</p><p style=\"text-align: center;\">&nbsp;<img src=\"http://139.196.239.213/thinkcmf/data/upload/ueditor/20161226/5860a9e25d555.jpg\"/></p><p style=\"text-indent: 28px\">Each game published by Gamepoch will be customized a perfect and efficient development plan. The promotion and development of “KOF14” Chinese licensed version breaks the tradition and take “the Esport against the game” mode . With the rapid development of Chinese esport to make the game&#39;s release more influential.</p><p>&nbsp;</p><h1 label=\"标题居左\" style=\"font-size: 32px; font-weight: bold; border-bottom-color: rgb(204, 204, 204); border-bottom-width: 2px; border-bottom-style: solid; padding: 0px 4px 0px 0px; text-align: left; margin: 0px 0px 10px;\"><strong><span style=\"font-size: 24px;\">The beginning of “Star Singularity”</span></strong></h1><p style=\"text-indent: 28px\">Da Takehito, President of SONY interactive entertainment (Shanghai) Co., Ltd, officially announced the establishment of “star singularity alliance”.</p><p style=\"text-align: center;\">&nbsp;<img src=\"http://139.196.239.213/thinkcmf/data/upload/ueditor/20161226/5860aa088c3e2.jpg\"/></p><p style=\"text-indent: 28px\">Offline store is one of the most closely way to combined with players. “Star singularity alliance” was set as a trinity comprehensive mode of &quot;experience, competitive and shopping&quot; to maximize the players’ feeling of the fun in games when the “star singularity” project was in progress. Gamepoch plans to expand various size of SONY PS4 and PSVR Game Café in the future, in order to expands the scale of “Star singularity alliance”. To makes the offline alliance become stronger and makes more players feel the charm of video game throughout the country.</p><p style=\"text-indent: 28px\">Anchored in China and keep the whole world in view. Gamepoch keeps looking for high-quality co-operation in the industry, fulfilling excellent win-win situation, developing outside industry co-operation, and expanding service business.</p><p style=\"text-indent: 28px\">Gamepoch will stick to building the high-quality game platform and delicate publishing, based on huge potential of Chinese game market, leading the import of excellent console game into China and even Asia with both abroad and domestic. We focus on console game service, directing people to share the getting-together, health and positivity of the games to make a new breakthrough for Chinese game market to be more family oriented and interactive.</p><p><br/></p>",
    "post_title": "Anchored in China and keep the whole world in view  ——Gamepoch appeared in PlayStation@China Publisher Developer Meeting",
    "post_excerpt": "  In October 24th, SONY launched PlayStation@ China Publisher &amp; Developer Meeting in Renaissance Shanghai Zhongshan Park  ",
    "post_status": "1",
    "comment_status": "1",
    "post_modified": "2016-12-26 13:18:44",
    "post_content_filtered": null,
    "post_parent": "0",
    "post_type": null,
    "post_mime_type": "",
    "comment_count": "0",
    "smeta": "{\"thumb\":\"5860adc91f4f9.jpg\"}",
    "post_hits": "0",
    "post_like": "0",
    "istop": "0",
    "recommended": "0",
    "post_net": "gamepoch.com",
    "tid": "1",
    "object_id": "1",
    "term_id": "1",
    "listorder": "1",
    "status": "1"
  }];

  res.send(dataArray);
});

module.exports = router;
